In [2]:
import tensorflow as tf

In [3]:
print(tf.version)

<module 'tensorflow_core._api.v2.version' from '/usr/local/lib/python3.6/site-packages/tensorflow_core/_api/v2/version/__init__.py'>


# Tensors
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

Data Types Include: float32, int32, string and others.

Shape: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.

# Creating Tensors
Below is an example of how to create some different tensors.

You simply define the value of the tensor and the datatype and you are good to go! It's worth mentioning that usually we deal with tensors of numeric data, it is quite rare to see string tensors.

For a full list of datatypes please refer to the following guide.

https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable

In [4]:
string = tf.Variable("string 1",tf.string)
number = tf.Variable(123,tf.int16)
float_num = tf.Variable(123.122,tf.float16)


# Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

Now we'll create some tensors of higher degrees/ranks.

In [5]:
rank1_tensor = tf.Variable("String1",tf.string)
rank2_tensor = tf.Variable([["string1" , "string2"],["string3","string4"]],tf.string)


To determine the rank of a tensor we can call the following method.

In [6]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [7]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of Tensors
Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To get the shape of a tensor we use the shape attribute.

In [9]:
rank2_tensor.shape

TensorShape([2, 2])

In [10]:
rank1_tensor.shape

TensorShape([])

Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: tensor[dim1, dim2, dim3]


In [11]:
matrix = [ [1,2,3,4],[5,6,7,8],[9,10,11,12]]
tensor = tf.Variable(matrix,tf.int32)
print(tf.rank(matrix))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(3, 4)


In [14]:
three = tensor[0,2]
print(three)
row1 = tensor[0]
print(row1)
column1 = tensor[:,0]
print(column1)
row2_row4 = tensor[1::2]
print(row2_row4)
column1_row_2_row3 = tensor[1:3,0]
print(column1_row_2_row3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 5 9], shape=(3,), dtype=int32)
tf.Tensor([[5 6 7 8]], shape=(1, 4), dtype=int32)
tf.Tensor([5 9], shape=(2,), dtype=int32)


# Types of Tensors

Variable
Constant
Placeholder
SparseTensor
With the execption of Variable all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.